-- CreateEnum
CREATE TYPE "RemoteApplicationStatus" AS ENUM ('REMOTE_APPLIED', 'REMOTE_SCREEN', 'REMOTE_INTERVIEW', 'REMOTE_OFFER', 'REMOTE_HIRED', 'REMOTE_REJECTED', 'REMOTE_NEW_LEAD', 'REMOTE_INTERNALLY_SUBMITTED', 'REMOTE_CANDIDATE_DECLINED_LOCATION', 'REMOTE_INTERVIEWING', 'REMOTE_APPROVED', 'REMOTE_MAYBE');

-- CreateEnum
CREATE TYPE "ApplicationStatus" AS ENUM ('APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED');

-- AlterTable
ALTER TABLE "ats_applications" ADD COLUMN     "status" "RemoteApplicationStatus" NOT NULL DEFAULT 'REMOTE_APPLIED';

-- AlterTable
ALTER TABLE "applications" ADD COLUMN     "status" "ApplicationStatus";
